OUT="C:/Users/housh/Documents/monoWeb/hex-empires/.claude/gdd/systems/combat.md"
BT=chr(96)
EM=chr(8212)
EN=chr(8211)
RS=chr(8217)
PM=chr(177)
MU=chr(215)
MI=chr(8722)
ARR=chr(8594)
NL=chr(10)
lines=[]
def L(s=""): lines.append(s)
L("# Combat " + EM + " Civ VII")
L()
L("**Slug:** " + BT + "combat" + BT)
L("**Bucket:** " + BT + "combat" + BT)
L("**Status:** " + BT + "draft" + BT)
L("**Confidence:** " + BT + "medium" + BT)
L("**Last verified:** " + BT + "2026-04-19" + BT)
L("**Authoring model:** " + BT + "claude-sonnet-4-6" + BT)
L()
L("---")
L("## Sources")
L()
L("Every factual claim in the sections below MUST trace to one of these, or be tagged " + BT + "[INFERRED]" + BT + " / " + BT + "[LLM-KNOWLEDGE-ONLY]" + BT + ".")
L()
L("- https://civilization.2k.com/civ-vii/game-guide/dev-diary/combat/ " + EM + " Firaxis Dev Diary #5: Combat")
L("- https://civilization.fandom.com/wiki/Strength_(Civ7) " + EM + " Fandom: Strength (Civ7) [403 on direct fetch; content surfaced via WebSearch]")
L("- https://civilization.fandom.com/wiki/Combat_(Civ7) " + EM + " Fandom: Combat (Civ7) [403 on direct fetch; content surfaced via WebSearch]")
L("- https://civilization.fandom.com/wiki/Land_unit_(Civ7) " + EM + " Fandom: Land unit (Civ7) [403 on direct fetch; content surfaced via WebSearch]")
L("- https://game8.co/games/Civ-7/archives/499026 " + EM + " Game8: Civ 7 Ground Combat Guide")
L("- https://game8.co/games/Civ-7/archives/499033 " + EM + " Game8: Civ 7 How to Defend and Conquer Cities")
L("- https://game8.co/games/Civ-7/archives/500086 " + EM + " Game8: Civ 7 Zone of Control")
L("- https://www.well-of-souls.com/civ/civ7_units.html " + EM + " Well of Souls: Civ VII Unit Analyst")
L("- https://screenrant.com/civ-7-new-combat-system-commanders-siege-warfare-explainer/ " + EM + " ScreenRant: Civ 7 New Combat System Explained")
L("- https://12gramsofcarbon.com/p/civ-7-war-strategy-and-tactics " + EM + " 12grams: War Strategy and Tactics (community)")
L("- https://www.gamesradar.com/games/strategy/civilization-7-heal-units/ " + EM + " GamesRadar: How to Heal Units in Civ 7")
L("- https://www.gamerant.com/civilization-vii-heal-units-guide-healing-unit-boost-heal-amount-increase-healing-civ-7/ " + EM + " GameRant: Civilization VII Heal Units Guide")
L("- https://www.well-of-souls.com/civ/civ7_terrain.html " + EM + " Well of Souls: Civ VII Terrain Analyst")
L()
L("**Source conflicts noted:** Two sources disagree on healing rates in enemy territory: one cites 5 HP/turn, another 10 HP/turn. Fandom wiki pages for Combat_(Civ7) and Strength_(Civ7) returned HTTP 403. Conflict flagged in Healing section.")
L()
L("---")
L()
L("## Purpose")
L()
L("Combat in Civ VII is the resolution engine for all military conflict between units. It retains Civ V" + RS + "s one-unit-per-tile model but adds a directional battlefront system and district-by-district siege. Commanders (covered separately in " + BT + "systems/commanders.md" + BT + ") provide the army-aggregation layer " + EM + " this doc covers the combat resolution engine.")
L()
L("---")
L("## Entities")
L()
L("- " + BT + "UnitState.hp" + BT + " " + EM + " (RW) " + EM + " current hit points (0" + EN + "100); reduces on combat hit")
L("- " + BT + "UnitState.combatStrength" + BT + " " + EM + " (R) " + EM + " base melee CS; modified at resolution time by terrain, flanking, support, health penalty, fortification")
L("- " + BT + "UnitState.rangedStrength" + BT + " " + EM + " (R) " + EM + " used for ranged attacks against land units; 0 for melee-only units")
L("- " + BT + "UnitState.bombardStrength" + BT + " " + EM + " (R) " + EM + " used for ranged attacks against naval units, fortified districts, and land units inside fortifications")
L("- " + BT + "UnitState.movement" + BT + " " + EM + " (RW) " + EM + " remaining movement points this turn; combat typically costs all remaining movement")
L("- " + BT + "UnitState.unitClass" + BT + " " + EM + " (R) " + EM + " " + BT + "melee | ranged | cavalry | siege | naval" + BT + "; determines ZoC, Swift eligibility, attack modes")
L("- " + BT + "UnitState.facing" + BT + " " + EM + " (RW) " + EM + " set on first melee engagement; determines flank/rear positions")
L("- " + BT + "UnitState.isFortified" + BT + " " + EM + " (RW) " + EM + " true when Fortify action used and unit has not moved; grants CS bonus on defense")
L("- " + BT + "Tile.defensiveBonus" + BT + " " + EM + " (R) " + EM + " CS modifier from terrain/feature on the tile being defended")
L("- " + BT + "Tile.fortifiedDistrictHp" + BT + " " + EM + " (RW) " + EM + " HP of fortification on a fortified district tile; base 100, +100 with walls")
L("- " + BT + "PlayerState.warSupport" + BT + " " + EM + " (RW) " + EM + " each point of negative war support grants +1 CS advantage to the opposing player")
L("- " + BT + "GameState.currentAge" + BT + " " + EM + " (R) " + EM + " some unit classes and wall types are age-gated")
L()
L("---")
L()
L("## Triggers")
L()
L("- On action **ATTACK** " + EM + " combat resolution fires immediately; attacker and defender both receive or deal damage; attacker expends remaining movement points.")
L("- On action **BOMBARD** " + EM + " attacker uses " + BT + "rangedStrength" + BT + " or " + BT + "bombardStrength" + BT + " depending on target type; defender does NOT return fire.")
L("- On action **FORTIFY** " + EM + " unit becomes immobile; gains +5 CS when defending; begins healing on subsequent turns.")
L("- On **END_TURN** " + EM + " healing ticks for all units that did not move or attack this turn.")
L("- On condition **district HP reaches 0** " + EM + " district walls are destroyed; tile becomes unfortified; occupying enemy unit may claim the tile.")
L("- On condition **all fortified districts destroyed AND unit moves onto City Center tile** " + EM + " settlement captured; enters unrest period.")
L()
L("---")
L("## Mechanics")
L()
L("### Unit Classes and Roles")
L()
L("Civ VII uses five land unit classes. There is no rock-paper-scissors bonus triangle between them by default (unlike Civ VI" + RS + "s anti-cavalry class mechanic). Spearman-line units retain a contextual bonus against cavalry [see Open Questions], but this is not a system-wide counter rule.")
L()
L("**Melee** (" + BT + "melee" + BT + "): Standard infantry. Uses " + BT + "combatStrength" + BT + " for both attack and defense. Subject to Zone of Control. Forms the battlefront anchor for flanking plays. Examples: Warrior (CS 20), Spearman (CS 25), Man-at-Arms (CS 40), Line Infantry (CS 50).")
L()
L("**Ranged** (" + BT + "ranged" + BT + "): Uses " + BT + "rangedStrength" + BT + " on offense; cannot perform melee attacks. Does NOT have Zone of Control. Range stat (typically 2). Returns fire only if the attacker is within range. Examples: Archer (ranged CS 10), Crossbowman (CS 25), Field Cannon (CS 35).")
L()
L("**Cavalry** (" + BT + "cavalry" + BT + "): High CS and high movement. Possesses **Swift** " + EM + " immune to Zone of Control from all units. Can move through enemy ZoC tiles without stopping. Excel at flanking and chasing ranged units. Examples: Horseman (CS 35), Knight (CS 45), Tank (CS 65).")
L()
L("**Siege** (" + BT + "siege" + BT + "): Functions like ranged but uses " + BT + "bombardStrength" + BT + " when attacking fortified districts, naval units, or land units inside fortifications. The **Siege** ability enables attacks on fortified districts to also damage the defending unit inside. Examples: Ballista (bombard CS 10), Catapult (CS 20), Trebuchet (CS 25), Howitzer (CS 45).")
L()
L("**Naval**: Ship units on water tiles and navigable rivers. Can ferry land units. Naval ranged units use " + BT + "bombardStrength" + BT + " against land units inside fortifications. Examples: Galley (CS 20), Battleship (CS 60).")
L()
L("### Combat Strength (CS)")
L()
L("Combat Strength governs melee combat output and melee defense. All modifiers are expressed as additive CS adjustments applied at resolution time. The attacker and defender each compute their effective CS before damage is calculated.")
L()
L("Unit hit points are standardized at **100 HP** maximum across all unit types.")
L()
L("**Wounded-unit penalty:** A unit" + RS + "s effective CS decreases as it takes damage. The penalty is approximately **" + MI + "1 CS per 10 HP lost**, beginning at 99 HP. Maximum penalty is **" + MI + "10 CS** when a unit is below 10 HP. This is a continuous linear penalty, not a step function. [Source: Fandom Strength_(Civ7), surfaced via search.]")
L()
L("### Damage Calculation")
L()
L("The exact algebraic formula Firaxis uses has not been published. From community reverse-engineering and search-surfaced Fandom content:")
L()
L("- Damage is determined by the **difference in effective CS** between attacker and defender.")
L("- Community data suggests: one-shot is **possible at approximately +23 CS difference**, **average around +30 CS difference**, and **guaranteed at approximately +39 CS difference**. [Source: Fandom Strength_(Civ7) via search " + EM + " approximate.]")
L("- Damage has a **random variance of " + PM + "30%**. This variance is larger than Civ VI (" + PM + "25%).")
L("- **Damage is capped at 100** per hit.")
L("- Both melee attacker and defender deal damage simultaneously. Ranged and bombard attacks are one-sided " + EM + " the target does NOT return fire.")
L("- The formula used in Civ VI was: " + BT + "Damage = 30 " + MU + " e^(StrengthDifference / 25) " + MU + " Random(0.75, 1.25)" + BT + ". Whether Civ VII uses the same base formula is **[INFERRED]**.")
L()
L("### Terrain Defense Bonuses")
L()
L("Terrain modifies the effective CS of the defending unit.")
L()
L("| Terrain / Feature | Effect |")
L("|---|---|")
L("| Rough terrain (hills, mountains) | +3 CS when defending [Fandom via search] |")
L("| Vegetated terrain (woods, jungle, forest) | +2 CS when defending [Fandom via search] |")
L("| Minor River (unit defending on the tile) | " + MI + "5 CS penalty [Well of Souls terrain doc] |")
L("| Difficult terrain general | Ends movement of units entering, regardless of remaining move points |")
L()
L("Whether cavalry suffers an additional context-specific CS penalty beyond the standard defender bonus in rough/vegetated terrain is [INFERRED] as strategically disadvantageous but the exact value is unconfirmed.")
L()
L("### Fortification Bonus")
L()
L("The **Fortify** action makes a unit immobile for the current turn and any subsequent turns until it moves. While fortified:")
L()
L("- The unit gains **+5 CS on defense**. [Source: Game8 Ground Combat Guide]")
L("- Fortification stacks with terrain defense bonuses.")
L("- A fortified unit inside a fortified district gains the district wall bonus in addition to the +5 CS personal fortification.")
L("- Fortification is lost when the unit moves.")
L("- Fortifying also triggers end-of-turn healing (see Healing section).")
L()
L("District walls provide an additional **+15 CS to defenders** inside fortified districts. [Source: Game8 How to Defend and Conquer Cities]")
L()
L("### Zone of Control (ZoC)")
L()
L("ZoC is an area-denial mechanic. Melee and siege units project ZoC into all adjacent tiles. An enemy unit entering a ZoC tile must stop immediately and may not move further that turn, even if movement points remain. [Source: Game8 Zone of Control guide]")
L()
L("Key ZoC rules:")
L()
L("- Only **melee** and **siege** units project ZoC. Ranged units do NOT project ZoC.")
L("- **Cavalry** possesses the **Swift** ability, making them immune to ZoC. They may move freely through ZoC tiles.")
L("- Ranged units are subject to ZoC from enemy melee/siege units (they can be locked in place).")
L("- A unit already in a ZoC tile at the start of its turn may attack or retreat, but cannot move further into a different ZoC tile without stopping.")
L("- ZoC does not prevent attacking; it prevents continuation of movement after entering the ZoC tile.")
L()
L("### Flanking and the Battlefront System")
L()
L("When a melee unit first attacks another unit, a **battlefront** is established. The defending unit" + RS + "s facing direction is set toward the attacker. Subsequent attacks from non-front directions gain a flanking bonus. [Source: Firaxis Dev Diary #5]")
L()
L("Flanking bonus tiers:")
L()
L("|  Attack direction | CS bonus to attacker |")
L("|---|---|")
L("| Front (same direction as established battlefront) | +0 CS |")
L("| Flank (90 degrees from battlefront) | +3 CS [INFERRED; exact value unconfirmed] |")
L("| Rear (180 degrees from battlefront) | +6 CS [INFERRED; exact value unconfirmed] |")
L()
L("**Flanking requires the Military Training technology** to unlock the battlefront mechanic. Before researching Military Training, attacks from any direction deal no flanking bonus. [Source: Game8 Ground Combat Guide]")
L()
L("The **Skirmish** promotion grants **+50% to any flanking bonus received**, making cavalry and mobile units significantly more dangerous when attacking from flank or rear positions. [Source: Fandom Combat_(Civ7) via search]")
L()
L("### Support Bonus")
L()
L("Friendly adjacent units provide a **+2 CS per adjacent friendly unit** bonus to the primary combatant. [Source: Game8 Ground Combat Guide]")
L()
L("Support bonus is additive with all other CS bonuses. A unit surrounded by 3 friendly units gains +6 CS in combat. The bonus applies to both attacker and defender independently (each receives support from their own adjacent friendlies only).")
L()
L("Support bonus does NOT require the friendly adjacent unit to take any action. The unit simply needs to be present on an adjacent tile and alive.")
L()
L("### Healing")
L()
L("Units heal at the end of a turn in which they did **not** move or attack. Healing requires surviving the turn with HP > 0. The fortify action triggers the healing rate as if the unit were in friendly territory. [Source: GamesRadar, GameRant]")
L()
L("| Territory type | Healing rate per turn |")
L("|---|---|")
L("| In a city (own or allied) | ~20 HP/turn [GamesRadar] |")
L("| Own or allied territory (outside city) | ~15 HP/turn [GamesRadar] |")
L("| Neutral territory | ~10 HP/turn [GamesRadar] |")
L("| Enemy territory | 5-10 HP/turn [Source conflict: GamesRadar 10 HP; another source 5 HP; see Sources] |")
L()
L("**Source conflict on enemy territory healing:** GamesRadar cites 10 HP/turn in enemy territory; a second source cites 5 HP/turn. The 10 HP value appears more often across community guides but is unconfirmed against a Firaxis primary source. Using 10 HP as working assumption; flag for re-verification.")
L()
L("Promotions and civilization bonuses can increase healing rates. The exact promotion names affecting healing are [INFERRED] to exist but are not fully catalogued here.")
L()
L("### Retreat")
L()
L("When a unit reaches 0 HP from combat, it is **eliminated** (removed from the map). There is no automatic tactical retreat to a safe tile in standard combat resolution. [INFERRED from Civ VI behavior; no explicit Civ VII documentation found]")
L()
L("Units may be **strategically withdrawn** by moving away from the enemy before combat, but this is a player action, not an automatic game mechanic. A unit that would be reduced to 0 HP has no automatic escape.")
L()
L("**Capture vs. kill:** Civilian units (Settlers, Builders, Scouts) are **captured** rather than killed when an enemy military unit enters their tile. They become a unit of the capturing player. Military combat units are always eliminated, never captured. [Source: Game8 Ground Combat Guide]")
L()
L("### Siege Mechanics")
L()
L("Settlements in Civ VII have **district tiles** that may be fortified. Each fortified district acts as an independent defensive structure with its own HP pool. [Source: Firaxis Dev Diary #5; ScreenRant]")
L()
L("**District HP values:**")
L()
L("- Base fortified district: **100 HP**")
L("- District with walls built: **200 HP** (+100 HP from walls) [Source: Game8 How to Defend and Conquer Cities]")
L()
L("**Siege sequence:**")
L()
L("1. Attacker must use siege units (or ranged units with bombard strength) to deplete district HP.")
L("2. Each district must be individually destroyed.")
L("3. Land units inside a fortified district cannot be directly melee-attacked until the district falls.")
L("4. Siege units with the **Siege** ability can damage both the district HP AND the unit inside simultaneously (split damage).")
L("5. Once all defending districts in a settlement are destroyed, the settlement is vulnerable.")
L("6. A military unit must physically move onto the **City Center tile** to capture the settlement.")
L("7. Captured settlement enters an **unrest period** during which output is reduced. [Source: ScreenRant]")
L()
L("**Walls grant +15 CS to defenders** inside the walled district while walls stand. [Source: Game8 How to Defend and Conquer Cities]")
L()
L("Ranged units without the Siege ability cannot bombard fortified districts effectively (they use rangedStrength not bombardStrength). Naval units with bombardStrength CAN bombard coastal districts. [Source: Firaxis Dev Diary #5]")
L()
L("### War Support")
L()
L("War Support is a player-level statistic tracking morale/legitimacy for an ongoing war. Negative War Support (below 0) penalizes the player militarily: each point of negative War Support grants the **opposing** player **+1 CS** in all combat. [Source: 12grams community guide]")
L()
L("War Support reduces when the player attacks settlements with civilian population, conducts surprise wars, or fails to achieve military objectives. It increases with military victories, strategic resources, and diplomacy. [INFERRED from community context; exact trigger values not sourced]")
L()
L("---")
L("## Formulas")
L()
L("### Effective CS Computation")
L()
L("Pseudocode for effective CS at resolution time:")
L()
L("```")
L("function effectiveCS(unit, tile, isFortified, adjacentFriendlyCount, flankingBonus, warSupportPenalty):")
L("    base = unit.combatStrength")
L("    wounded = floor((100 - unit.hp) / 10) * -1   # 0 at full HP, -10 at <= 10 HP")
L("    terrain = tile.defensiveBonus                 # +3 hills, +2 forest, -5 river, etc.")
L("    fortify  = +5 if isFortified else 0")
L("    walls    = +15 if insideFortifiedDistrict and districtHasWalls else 0")
L("    support  = adjacentFriendlyCount * 2")
L("    flanking = flankingBonus                      # 0 front, +3 flank, +6 rear (INFERRED)")
L("    warAdv   = -warSupportPenalty if warSupportPenalty > 0 else 0   # opponent gets +1 CS per -1 warSupport")
L("    return base + wounded + terrain + fortify + walls + support + flanking + warAdv")
L("```")
L()
L("### Damage Formula")
L()
L("The formula used in Civ VI (which Civ VII likely inherits [INFERRED]):")
L()
L("```")
L("Damage = 30 * e^(StrengthDiff / 25) * Random(0.75, 1.25)")
L("StrengthDiff = attackerEffectiveCS - defenderEffectiveCS")
L("Result capped at 100. Floored at 0 (no negative damage).")
L("```")
L()
L("Both attacker and defender calculate damage simultaneously in melee. For ranged/bombard, only the attacker deals damage.")
L()
L("### Representative Unit CS Values")
L()
L("| Unit | Class | Base CS |")
L("|---|---|---|")
L("| Warrior | melee | 20 |")
L("| Spearman | melee | 25 |")
L("| Man-at-Arms | melee | 40 |")
L("| Musketman | melee | 45 |")
L("| Line Infantry | melee | 50 |")
L("| Archer | ranged | 10 (ranged CS) |")
L("| Crossbowman | ranged | 25 (ranged CS) |")
L("| Field Cannon | ranged | 35 (ranged CS) |")
L("| Horseman | cavalry | 35 |")
L("| Knight | cavalry | 45 |")
L("| Tank | cavalry | 65 |")
L("| Ballista | siege | 10 (bombard CS) |")
L("| Catapult | siege | 20 (bombard CS) |")
L("| Trebuchet | siege | 25 (bombard CS) |")
L("| Howitzer | siege | 45 (bombard CS) |")
L("| Galley | naval | 20 |")
L("| Battleship | naval | 60 |")
L()
L("[Source: Well of Souls Unit Analyst, cross-checked with Game8]")
