var fs=require('fs');
var p='C:/Users/housh/Documents/monoWeb/hex-empires/.claude/gdd/systems/combat.md';
fs.writeFileSync(p,'','utf8');
function a(s){fs.appendFileSync(p,(s===undefined?'':s)+'\n','utf8');}
a('# Combat — Civ VII');
a('');
a('**Slug:** `combat`');
a('**Bucket:** `combat`');
a('**Status:** `draft`');
a('**Confidence:** `medium`');
a('**Last verified:** `2026-04-19`');
a('**Authoring model:** `claude-sonnet-4-6`');
a('');
a('---');
a('');
a('## Sources');
a('');
a('Every factual claim in the sections below MUST trace to one of these, or be tagged `[INFERRED]` / `[LLM-KNOWLEDGE-ONLY]`.');
a('');
a('- https://civilization.2k.com/civ-vii/game-guide/dev-diary/combat/ — Firaxis Dev Diary #5: Combat');
a('- https://civilization.fandom.com/wiki/Strength_(Civ7) — Fandom: Strength (Civ7) [403 on direct fetch; content surfaced via WebSearch]');
a('- https://civilization.fandom.com/wiki/Combat_(Civ7) — Fandom: Combat (Civ7) [403 on direct fetch; content surfaced via WebSearch]');
a('- https://game8.co/games/Civ-7/archives/499026 — Game8: Civ 7 Ground Combat Guide');
a('- https://game8.co/games/Civ-7/archives/499033 — Game8: Civ 7 How to Defend and Conquer Cities');
a('- https://game8.co/games/Civ-7/archives/500086 — Game8: Civ 7 Zone of Control');
a('- https://www.well-of-souls.com/civ/civ7_units.html — Well of Souls: Civ VII Unit Analyst (numeric CS values)');
a('- https://screenrant.com/civ-7-new-combat-system-commanders-siege-warfare-explainer/ — ScreenRant: Civ 7 New Combat System Explained');
a('- https://12gramsofcarbon.com/p/civ-7-war-strategy-and-tactics — 12grams: Civ 7 War Strategy and Tactics (community analysis)');
a('- https://www.gamesradar.com/games/strategy/civilization-7-heal-units/ — GamesRadar: How to Heal Units in Civ 7');
a('- https://www.gamerant.com/civilization-vii-heal-units-guide-healing-unit-boost-heal-amount-increase-healing-civ-7/ — GameRant: Civilization VII Heal Units Guide');
a('- https://www.well-of-souls.com/civ/civ7_terrain.html — Well of Souls: Civ VII Terrain Analyst');
a('');
a('**Source conflicts noted:** Two sources disagree on healing rates in enemy territory: one cites 5 HP/turn, another 10 HP/turn. The conflict is flagged in the Healing section. Fandom wiki pages for Combat_(Civ7) and Strength_(Civ7) returned HTTP 403; all content attributed to those pages was surfaced via Google search snippet text.');
a('');
a('---');
a('');
a('## Purpose');
a('');
a('Combat in Civ VII is the resolution engine for all military conflict between units. It retains Civ V’s one-unit-per-tile model but adds a directional battlefront system (flanking by position) and decomposes city capture into district-by-district siege. Commanders (covered separately in `systems/commanders.md`) provide the army-aggregation layer — this doc covers the combat resolution engine that commanders interact with but do not own.');
a('---');
a('');
a('## Entities');
a('');
a('- `UnitState.hp` — (RW) — current hit points (0–100); reduces on combat hit; determines wounded-unit CS penalty');
a('- `UnitState.combatStrength` — (R) — base melee CS; modified at resolution time by terrain, flanking, support, health penalty, fortification');
a('- `UnitState.rangedStrength` — (R) — used for ranged attacks against land units; 0 for melee-only units');
a('- `UnitState.bombardStrength` — (R) — used for ranged attacks against naval units, fortified districts, and land units inside fortifications');
a('- `UnitState.movement` — (RW) — remaining movement points this turn; combat typically costs all remaining movement');
a('- `UnitState.unitClass` — (R) — `melee | ranged | cavalry | siege | naval`; determines ZoC, Swift eligibility, attack modes');
a('- `UnitState.facing` — (RW) — set on first melee engagement; determines which adjacent tiles are flank/rear positions');
a('- `UnitState.isFortified` — (RW) — true when unit has used the Fortify action and not moved; grants CS bonus on defense');
a('- `Tile.defensiveBonus` — (R) — CS modifier from terrain/feature on the tile being defended');
a('- `Tile.fortifiedDistrictHp` — (RW) — HP of fortification on a fortified district tile (0 = walls destroyed); base 100, +100 with walls');
a('- `PlayerState.warSupport` — (RW) — war support score; each point of negative war support grants +1 CS advantage to the opposing player in combat [community source]');
a('- `GameState.currentAge` — (R) — some unit classes and wall types are age-gated');
a('');
a('---');
a('');
a('## Triggers');
a('');
a('- On action **ATTACK** (player dispatches a unit to attack an adjacent or ranged-eligible tile) — combat resolution fires immediately; attacker and defender both receive or deal damage; attacker expends remaining movement points.');
a('- On action **BOMBARD** (ranged or siege unit fires on an in-range target) — attacker uses `rangedStrength` or `bombardStrength` depending on target type; defender does NOT return fire.');
a('- On action **FORTIFY** (unit uses its Fortify action) — unit becomes immobile; gains +5 CS when defending; begins healing on subsequent turns.');
a('- On **END_TURN** (player ends turn) — healing ticks for all units that did not move or attack this turn; `hp` increments by territory-dependent heal amount.');
a('- On condition **district HP reaches 0** — district walls are destroyed; fortified district tile converts to unfortified; occupying enemy unit may claim the tile.');
a('- On condition **all fortified districts destroyed AND unit moves onto City Center tile** — settlement is captured; enters unrest period; production temporarily blocked.');
a('');
a('---');
