"""
Aggregate audit reports → convergence tracker + GDD Mapping sections.

Parses every `.codex/gdd/audits/<slug>.md` file, extracts findings (F-0N
entries with status/severity/location/title), and:

1. Populates `.codex/gdd/convergence-tracker.md` findings-by-severity tables
2. Updates each `.codex/gdd/systems/<slug>.md` § "Mapping to hex-empires"

The script is idempotent — re-run whenever new audits land.

## Usage

    python .codex/scripts/aggregate-audits.py [--dry-run]
    python .codex/scripts/aggregate-audits.py --check

## What qualifies as an audit

Files in `.codex/gdd/audits/<slug>.md` with:
- `## Detailed findings` section
- One or more `### F-NN: ... — STATUS` entries

Each finding block is parsed for:
- F-ID (F-01..F-99)
- title (after colon, before em-dash)
- status (DIVERGED | MATCH | CLOSE | MISSING | EXTRA)
- severity (HIGH | MED | LOW) — from `**Severity:**` line
- effort (S | M | L) — from `**Effort:**` line
- location (from `**Location:**` line)
- VII says, Engine does, Gap, Recommendation (for Mapping summary)

Audit-meta filenames (starting with `_`) are skipped.

## Exit codes

- 0: success
- 1: no audits found
- 2: malformed arg
- 3: generated files are stale (`--check`)
"""
import argparse
import os
import re
import sys
from pathlib import Path


AUDIT_DIR = Path('.codex/gdd/audits')
SYSTEMS_DIR = Path('.codex/gdd/systems')
TRACKER = Path('.codex/gdd/convergence-tracker.md')

FINDING_RE = re.compile(
    r'^###\s+F-(\d+):\s*(.+?)\s*(?:—|--)\s*'
    r'(MATCH|CLOSE|DIVERGED|MISSING|EXTRA)(?:\s*\([^)]*\))?\s*$',
    re.MULTILINE,
)

META_RE_LOCATION = re.compile(r'^\*\*Location:\*\*\s*(.+?)$', re.MULTILINE)
META_RE_SEVERITY = re.compile(r'^\*\*Severity:\*\*\s*(HIGH|MED|LOW)', re.MULTILINE)
META_RE_EFFORT = re.compile(r'^\*\*Effort:\*\*\s*([SML])', re.MULTILINE)

STATUS_EMOJI = {
    'MATCH': '✓',
    'CLOSE': '≈',
    'DIVERGED': '⚠',
    'MISSING': '⊘',
    'EXTRA': '✗',
}

SEVERITY_PRIORITY = {
    'HIGH': 0,
    'MED': 1,
    'LOW': 2,
    'UNK': 3,
}

ACTIVE_STATUS_PRIORITY = {
    'DIVERGED': 0,
    'MISSING': 1,
    'CLOSE': 2,
    'EXTRA': 3,
    'MATCH': 4,
}


def parse_audit(path):
    """Yield finding dicts from one audit file."""
    content = path.read_text(encoding='utf-8', errors='replace')
    slug = path.stem

    findings = []
    # Find all F-NN headers; split the file by these headers to get bodies
    header_matches = list(FINDING_RE.finditer(content))
    if not header_matches:
        return slug, []

    for i, m in enumerate(header_matches):
        fid = f"F-{m.group(1).zfill(2)}"
        title = m.group(2).strip()
        status = m.group(3)
        # Body: from end-of-header to start of next header (or end of file)
        body_start = m.end()
        body_end = header_matches[i + 1].start() if i + 1 < len(header_matches) else len(content)
        body = content[body_start:body_end]

        sev_m = META_RE_SEVERITY.search(body)
        eff_m = META_RE_EFFORT.search(body)
        loc_m = META_RE_LOCATION.search(body)

        findings.append({
            'slug': slug,
            'fid': fid,
            'title': title,
            'status': status,
            'severity': sev_m.group(1) if sev_m else 'UNK',
            'effort': eff_m.group(1) if eff_m else 'UNK',
            'location': loc_m.group(1).strip() if loc_m else '',
        })

    return slug, findings


def tally_audit(findings):
    """Return status counts for one audit."""
    t = {'MATCH': 0, 'CLOSE': 0, 'DIVERGED': 0, 'MISSING': 0, 'EXTRA': 0}
    for f in findings:
        t[f['status']] = t.get(f['status'], 0) + 1
    return t


def select_top_finding(findings):
    """Return the highest-severity active finding for mapping summaries."""
    if not findings:
        return None
    candidates = [f for f in findings if f['status'] != 'MATCH'] or findings
    return min(
        candidates,
        key=lambda f: (
            SEVERITY_PRIORITY.get(f['severity'], 9),
            ACTIVE_STATUS_PRIORITY.get(f['status'], 9),
            f['fid'],
        ),
    )


def generate_tracker_body(all_findings, per_audit_tallies):
    """Generate the convergence tracker markdown."""
    lines = []
    lines.append("# hex-empires → Civ VII Convergence Tracker\n")
    lines.append(
        "**Purpose.** One-page master punch list of every finding from every audit. "
        "Sort by priority to decide what to implement next. Tick off as PRs land.\n"
    )
    lines.append(
        "**Commitment:** hex-empires is a FULL CLONE of Civ VII (see "
        "[`commitment.md`](commitment.md)). Every DIVERGED/MISSING finding is a "
        "must-fix; every CLOSE is a must-tune.\n"
    )
    lines.append(
        "**Updates:** regenerated by `.codex/scripts/aggregate-audits.py` after "
        "new audit files land in `.codex/gdd/audits/`.\n"
    )
    lines.append("\n---\n")

    # Audit coverage
    lines.append("\n## Audit coverage\n")
    lines.append("| System | Audit file | Findings | Status tally |")
    lines.append("|---|---|---|---|")
    all_slugs = sorted(set(f['slug'] for f in all_findings))
    for slug in all_slugs:
        t = per_audit_tallies[slug]
        tally_str = f"{t['MATCH']}M / {t['CLOSE']}C / {t['DIVERGED']}D / {t['MISSING']}X / {t['EXTRA']}E"
        count = sum(t.values())
        lines.append(
            f"| {slug} | `.codex/gdd/audits/{slug}.md` | {count} | {tally_str} |"
        )
    lines.append(f"\n**Audits completed:** {len(all_slugs)} / 26\n")

    lines.append("\n---\n")

    # Findings by severity
    for sev in ('HIGH', 'MED', 'LOW'):
        lines.append(f"\n## {sev}-severity findings\n")
        filt = [f for f in all_findings if f['severity'] == sev]
        if not filt:
            lines.append("_(none)_\n")
            continue
        lines.append("| System | F-ID | Title | Status | Effort | Location |")
        lines.append("|---|---|---|---|---|---|")
        for f in sorted(filt, key=lambda x: (x['slug'], x['fid'])):
            loc = f['location'].replace('|', '\\|')[:80]
            title = f['title'].replace('|', '\\|')[:60]
            lines.append(
                f"| {f['slug']} | {f['fid']} | {title} | "
                f"{STATUS_EMOJI.get(f['status'], '?')} {f['status']} | {f['effort']} | "
                f"{loc} |"
            )
        lines.append("")

    lines.append("\n---\n")

    # Running totals
    total_tally = {'MATCH': 0, 'CLOSE': 0, 'DIVERGED': 0, 'MISSING': 0, 'EXTRA': 0}
    for t in per_audit_tallies.values():
        for k, v in t.items():
            total_tally[k] = total_tally.get(k, 0) + v

    lines.append("\n## Running totals\n")
    lines.append("| Status | Count |")
    lines.append("|---|---|")
    for k, v in total_tally.items():
        lines.append(f"| {k} | {v} |")
    lines.append(f"| **Total findings** | **{sum(total_tally.values())}** |")

    lines.append("")
    lines.append(f"\nImplementation progress: 0 / {sum(total_tally.values())} findings resolved (0%).\n")

    lines.append("\n---\n")
    lines.append(
        "\n## Next recommended action\n\n"
        "1. Read the top HIGH-severity / low-effort rows first — these are "
        "highest-ROI fixes.\n"
        "2. Pick a finding. Implement. Ink off (manual edit below).\n"
        "3. Re-run `python .codex/scripts/aggregate-audits.py` when new audits "
        "land to refresh the tables.\n"
    )

    return '\n'.join(lines) + '\n'


def generate_mapping_section(slug, findings):
    """Generate the Mapping-to-hex-empires section for one system."""
    t = tally_audit(findings)
    tally_str = (
        f"{t['MATCH']} MATCH / {t['CLOSE']} CLOSE / {t['DIVERGED']} DIVERGED / "
        f"{t['MISSING']} MISSING / {t['EXTRA']} EXTRA"
    )
    top = select_top_finding(findings)
    top_str = (
        f"{top['fid']} — {top['title']} ({top['status']}, {top['severity']})"
        if top else "_(no findings)_"
    )

    # Convergence status heuristic
    if t['DIVERGED'] > 0:
        status = f"Divergent — {t['DIVERGED']} finding(s) require(s) architectural refactor"
    elif t['MISSING'] > 0:
        status = f"Partial — {t['MISSING']} VII mechanic(s) absent"
    elif t['CLOSE'] > 0:
        status = f"Close — {t['CLOSE']} numeric/detail adjustment(s) pending"
    elif t['EXTRA'] > 0:
        status = f"Has legacy — {t['EXTRA']} Civ-VI-ism(s) to retire"
    else:
        status = "Full MATCH ✓"

    lines = [
        "## Mapping to hex-empires",
        "",
        f"**Status tally:** {tally_str}",
        f"**Audit:** [.codex/gdd/audits/{slug}.md](../audits/{slug}.md)",
        f"**Highest-severity finding:** {top_str}",
        f"**Convergence status:** {status}",
        "",
        f"_(Full details in audit file. {len(findings)} total finding(s). "
        "Regenerated by `.codex/scripts/aggregate-audits.py`.)_",
        "",
    ]
    return '\n'.join(lines)


def update_system_mapping(slug, findings, dry_run, check):
    """Replace the Mapping-to-hex-empires section in systems/<slug>.md."""
    path = SYSTEMS_DIR / f'{slug}.md'
    if not path.exists():
        return False, f"systems/{slug}.md does not exist"

    content = path.read_text(encoding='utf-8')
    new_section = generate_mapping_section(slug, findings)

    # Match the existing "## Mapping to hex-empires" section (until next ## or end)
    pattern = re.compile(
        r'^## Mapping to hex-empires\s*$.*?(?=^## |\Z)',
        re.MULTILINE | re.DOTALL
    )
    if pattern.search(content):
        new_content = pattern.sub(new_section + '\n', content, count=1)
    else:
        # Section missing — append before end
        new_content = content.rstrip() + '\n\n' + new_section

    if new_content == content:
        return True, "unchanged"
    if check:
        return False, "stale"
    if not dry_run:
        path.write_text(new_content, encoding='utf-8')
    return True, "updated"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--dry-run', action='store_true', help='Preview changes; do not write')
    ap.add_argument('--check', action='store_true', help='Fail if generated files are not up to date')
    args = ap.parse_args()
    if args.dry_run and args.check:
        print("ERROR: --dry-run and --check are mutually exclusive", file=sys.stderr)
        return 2

    audit_files = [
        p for p in AUDIT_DIR.glob('*.md')
        if not p.name.startswith('_') and p.name != 'audit-process.md'
    ]
    if not audit_files:
        print("ERROR: no audit files found in .codex/gdd/audits/", file=sys.stderr)
        return 1

    print(f"Audits found: {len(audit_files)}")

    all_findings = []
    per_audit_tallies = {}
    system_update_results = []

    for path in sorted(audit_files):
        slug, findings = parse_audit(path)
        if not findings:
            print(f"  {slug}.md: NO FINDINGS PARSED — check audit structure")
            continue
        per_audit_tallies[slug] = tally_audit(findings)
        all_findings.extend(findings)

        ok, msg = update_system_mapping(slug, findings, args.dry_run, args.check)
        system_update_results.append((slug, ok, msg))
        print(f"  {slug}.md: {len(findings)} findings ({per_audit_tallies[slug]}) → systems/ {msg}")

    # Generate tracker
    tracker_body = generate_tracker_body(all_findings, per_audit_tallies)
    tracker_stale = False
    if args.check:
        existing_tracker = TRACKER.read_text(encoding='utf-8') if TRACKER.exists() else ''
        if existing_tracker != tracker_body:
            tracker_stale = True
            print(f"\nTracker stale: {TRACKER}")
        else:
            print(f"\nTracker up to date: {TRACKER}")
    elif args.dry_run:
        print(f"\n=== [dry-run] tracker preview ({len(tracker_body)} bytes) ===")
        print(tracker_body[:500] + '\n...(truncated)...')
    else:
        TRACKER.write_text(tracker_body, encoding='utf-8')
        print(f"\nTracker written: {TRACKER} ({len(tracker_body)} bytes)")

    print(f"\nTotal findings: {len(all_findings)}")
    total = {'MATCH': 0, 'CLOSE': 0, 'DIVERGED': 0, 'MISSING': 0, 'EXTRA': 0}
    for t in per_audit_tallies.values():
        for k, v in t.items():
            total[k] = total.get(k, 0) + v
    print(f"By status: {total}")
    sev_counts = {'HIGH': 0, 'MED': 0, 'LOW': 0, 'UNK': 0}
    for f in all_findings:
        sev_counts[f['severity']] = sev_counts.get(f['severity'], 0) + 1
    print(f"By severity: {sev_counts}")
    stale_systems = [slug for slug, ok, msg in system_update_results if msg == "stale"]
    if args.check and (tracker_stale or stale_systems):
        if stale_systems:
            print(f"Stale system mappings: {', '.join(stale_systems)}")
        return 3
    return 0


if __name__ == '__main__':
    sys.exit(main())
